
# [debug]
# print_events = true
# render_timer = true

[font]
size = 10.5

[font.normal]
family = "CaskaydiaCove NF"

[[keyboard.bindings]]
action = "CreateNewWindow"
key = "T"
mods = "Alt"

[terminal.shell]
args = ["-NoLogo -ExecutionPolicy Unrestricted"]
program = "pwsh"

[window]
opacity = 0.95

# [window.cursor.style]
# shape = "Beam"

[general]
import = ["./themes/themes/gruvbox_dark.yaml"]

[terminal]
