# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](color_orange)\
$sudo\
$directory\
[](fg:color_orange bg:color_aqua)\
$git_branch\
$git_status\
$git_metrics\
[](fg:color_aqua bg:color_blue)\
$python\
[](fg:color_blue bg:color_bg3)\
$fill\
$time\
$cmd_duration\
[ ](fg:color_bg3)\
$line_break$character"""

palette = 'gruvbox_dark'

add_newline = false

[palettes.gruvbox_dark]
color_fg0    = '#fbf1c7'
color_bg1    = '#3c3836'
color_bg3    = '#665c54'
color_blue   = '#458588'
color_aqua   = '#689d6a'
color_green  = '#98971a'
color_orange = '#d65d0e'
color_purple = '#b16286'
color_red    = '#cc241d'
color_yellow = '#d79921'

[sudo]
disabled = false
symbol = '󱐋'
format = '[$symbol]($style)'
style = "fg:color_fg0 bg:color_orange"

[directory]
style = "fg:color_fg0 bg:color_orange"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music"     = "󰝚 "
"Pictures"  = " "
"Developer" = "󰲋 "

[character]
disabled = false
success_symbol = '[](bold fg:color_green)'
error_symbol = '[](bold fg:color_red)'
vimcmd_symbol = '[](bold fg:color_green)'
vimcmd_replace_one_symbol = '[](bold fg:color_purple)'
vimcmd_replace_symbol = '[](bold fg:color_purple)'
vimcmd_visual_symbol = '[](bold fg:color_yellow)'

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[cmake]
disabled = true

[nodejs]
disabled = true

[rust]
disabled = true

[python]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol $virtualenv ](fg:color_fg0 bg:color_blue)]($style)'

[git_branch]
symbol = ""
style = "bg:color_aqua"
format = '[[ $symbol $branch ](fg:color_fg0 bg:color_aqua)]($style)'

[git_status]
style = "bg:color_aqua"
format = '[[($all_status$ahead_behind )](fg:color_fg0 bg:color_aqua)]($style)'

[git_metrics]
disabled = false
format = '[(+$added )]($added_style)[(-$deleted )]($deleted_style)'
added_style = "fg:color_fg0 bg:color_aqua"
deleted_style = "fg:color_fg0 bg:color_aqua"

[fill]
symbol = ' '
style = "bg:color_bg3"

[time]
disabled = false
time_format = "%T"
format = '[[  $time ](fg:color_fg0 bg:color_bg3)]($style)'

[cmd_duration]
disabled = false
show_milliseconds = true
style = "bg:color_bg1"
format = '[[󰔟 $duration](fg:color_fg0 bg:color_bg3)]($style)'

[line_break]
disabled = false

[username]
disabled = true

[os]
style = "bg:color_orange fg:color_fg0"

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"
